/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const card: string;
const main: string;
const pre: string;
const readTheDocs: string;

export {
	card,
	main,
	pre,
	readTheDocs
};

export default {
	card,
	main,
	pre,
	readTheDocs
};
